server:
  port: 8090

spring:
  application:
    name: svc-inventory
  data:
    mongodb:
      uri: ${MONGOURI}

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
